# Generated by Django 3.0.3 on 2020-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedata',
            name='feedback',
            field=models.DateField(default='2020-08-25'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='last_visit',
            field=models.DateField(default='2020-08-25'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='request_date',
            field=models.DateField(default='2020-08-25'),
        ),
    ]
