# Generated by Django 3.1 on 2020-09-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_app', '0002_auto_20200825_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedata',
            name='feedback',
            field=models.DateField(default='2020-09-03'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='last_visit',
            field=models.DateField(default='2020-09-03'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='request_date',
            field=models.DateField(default='2020-09-03'),
        ),
    ]
